apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: karpenter-demo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: karpenter-demo
  minReplicas: 2
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 0   # 🚀 no waiting
      policies:
      - type: Percent
        value: 100                    # 🚀 remove all extra pods fast
        periodSeconds: 5             # every 15 sec
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
